# Generated by Django 4.1.1 on 2022-10-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="views",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
