# Generated by Django 4.1.1 on 2022-10-05 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boards", "0003_post_updated_by_post_updated_dt_alter_topic_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="updated_dt",
            field=models.DateTimeField(null=True),
        ),
    ]
